// vulkan_renderer/src/shaders.rs — compiled SPIR-V bytecode
//
// Generated by Meson build from GLSL sources in shaders/.
// If glslc is unavailable, these will be empty and nothing renders.

pub static VERT_SPV: &[u8] = include_bytes!("vert.spv");
pub static FRAG_SPV: &[u8] = include_bytes!("frag.spv");
